AutomatedTellerMachine/AutomatedTellerMachine/Controllers/CheckingAccountController.cs
using AutomatedTellerMachine.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    public class CheckingAccountController : Controller
    {
        // GET: CheckingAccount
        public ActionResult Index()
        {
            return Redirect("Home/Index");
        }

        //GET: CheckingAccount/Details/5
        public ActionResult Details()
        {
            var checkingAccount = new CheckingAccount { AccountNumber = "0000123456", FirstName = "Michael", LastName = "Sullivan", Balance = 500 };
            return View(checkingAccount);
        }

        //GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        //POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
            
        }




    }
}

AutomatedTellerMachine/AutomatedTellerMachine/Controllers/HomeController.cs
using AutomatedTellerMachine.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;

namespace AutomatedTellerMachine.Controllers
{
    public class HomeController : Controller
    {
        //GET: /Home/Index
        public ActionResult Index()
        {
            return View();
        }


        //GET: /Home/About
        public ActionResult About()
        {
            ViewBag.Message = "The Countries which Summer Time Bank operates in.";

            ViewBag.Countries = new List<String>()
            {
                "India",
                "United States",
                "Canada",
                "Kenya"

            };

            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            ViewBag.CustomerMessage = "Having trouble? Send us a message.";

            return View();
        }
        [HttpPost]
        public ActionResult Contact(string customerMessage)
        {

            SqlCommand cmd = new SqlCommand();

            ViewBag.CustomerMessage = "Thanks, we got your message !";

            var database = new Database();
            
            cmd.CommandText = "INSERT INTO  dbo.comments (message) VALUES ('"+ customerMessage + "')";

            using (SqlConnection conn =
            new SqlConnection(database.connectionString))
            {
                conn.Open();
                cmd.Connection = conn;

                try
                {
                    
                    cmd.ExecuteNonQuery();
                    conn.Close();

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
        
          return View();
        }

        //GET: /Home/Serial/lower
        public ActionResult Serial(string letterCase)
        {
            var serial = "STB 18.01.30.05";

            if( letterCase == "lower")
            {
                return Content(serial.ToLower());
            }

            return Content(serial);
        }
    }
}

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<h2>Countries List</h2>

<ul>
    @foreach (String strCountry in ViewBag.Countries)
    {
        <li>@strCountry</li>
    }
</ul>

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    5798 Ellison Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@stbank.com">Support@stbank.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@stbank.com">Marketing@stbank.com</a>
</address>

<h3>@ViewBag.CustomerMessage</h3>
<form method="post">
    <div class="container">

        <div class="align-top">
            <textarea name="customerMessage"></textarea>
        </div>

        <div class="align-bottom">
            <input type="submit" value="Send" />
        </div>   
        
    </div>
</form>

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-12 margin-top-20">
        <span>You are using @Request.Browser.Browser, and that's OK!</span>
    </div>
    <div class="col-md-12">
        <span> Email us at support@summertimebank.com if you have any problems.</span>
    </div>
    <div class="col-md-12">
        <span> Or send a tweet to @@summertimebank</span>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary brn-large btn-block"><span class="glyphicon glyphicon-circle-arrow-down"></span> Withdrawal</a>
        <a href="#" class="btn btn-primary brn-large btn-block"><span class="glyphicon glyphicon-flash"></span> Quick Cash $100</a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary brn-large btn-block">
            <span class="glyphicon glyphicon-question-sign"></span> Balance Inquiry</a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary brn-large btn-block"><span class="glyphicon glyphicon-print"></span> Print Statement</a>
        <a href="#" class="btn btn-primary brn-large btn-block"><span class="glyphicon glyphicon-transfer"></span> Transfer Funds</a>
        <a href="#" class="btn btn-primary brn-large btn-block"><span class="glyphicon glyphicon-circle-arrow-up"></span> Deposit</a>
    </div>
</div>